import { z } from 'zod';
import { OutreachChannelSchema, OutreachStatusSchema } from '../enums.js';

/**
 * Schema for a single outreach draft (DM, email, or comment).
 *
 * Mirrors the `outreach_drafts` Drizzle table. One row per
 * (commit_marketing_run × influencer × channel). Drafts are
 * generated by the `outreach-draft-agent` and never auto-sent —
 * the user copies, marks sent, and (eventually) the system
 * listens for responses.
 *
 * `channel` and `status` derive from the Drizzle pgEnums via the
 * shared `enums.ts` file so the database column type and the Zod
 * validator stay in sync.
 */
export const OutreachDraftSchema = z.object({
  id: z.string().uuid(),
  commitMarketingRunId: z.string().uuid(),
  influencerId: z.string().uuid(),
  assetId: z.string().uuid().nullable(),
  channel: OutreachChannelSchema,
  draftText: z.string().min(1),
  status: OutreachStatusSchema,
  createdAt: z.date(),
  updatedAt: z.date(),
});
export type OutreachDraft = z.infer<typeof OutreachDraftSchema>;

export const OutreachDraftInsertSchema = z.object({
  commitMarketingRunId: z.string().uuid(),
  influencerId: z.string().uuid(),
  assetId: z.string().uuid().optional(),
  channel: OutreachChannelSchema,
  draftText: z.string().min(1),
  status: OutreachStatusSchema.default('drafted'),
});
export type OutreachDraftInsert = z.infer<typeof OutreachDraftInsertSchema>;

/**
 * Status update payload for `POST /api/outreach/:id/mark-sent`.
 * Restricts the allowed transitions to `copied` and `sent` so
 * the user can't accidentally roll a draft back to `drafted`
 * via the public API.
 */
export const OutreachStatusUpdateSchema = z.object({
  status: z.enum(['copied', 'sent']),
});
export type OutreachStatusUpdate = z.infer<typeof OutreachStatusUpdateSchema>;
