import { task } from '@renderinc/sdk/workflows';
import { eq } from 'drizzle-orm';
import * as schema from '@launchkit/shared';
import type { AssetType } from '@launchkit/shared';
import { database as db } from '../lib/database.js';
import { projectProgressPublisher } from '../lib/project-progress-publisher.js';
import { enqueueReviewJob } from '../lib/review-enqueue.js';
import { AllAssetsInputSchema, type AllAssetsInput } from './input-schemas.js';
import { generateWrittenAsset } from './generate-written-asset.js';
import { generateImageAsset } from './generate-image-asset.js';
import { generateVideoAsset } from './generate-video-asset.js';
import { generateAudioAsset } from './generate-audio-asset.js';
import { generateWorldScene } from './generate-world-scene.js';

/**
 * Parent task that replaces `fanOutGeneration` + `checkAndTriggerReview`
 * from the worker's BullMQ path.
 *
 * Flow:
 *
 *   1. Read every queued asset for the project from the DB.
 *   2. Publish a `phase_start: generating` progress event.
 *   3. Dispatch each asset to the appropriate child task via run
 *      chaining. Because we call the child task function inside this
 *      task's body, each call spawns a new chained run on its own
 *      instance — `generateWrittenAsset(...)` lands on a `starter`
 *      box, `generateVideoAsset(...)` lands on a `pro` box, and so
 *      on. This is where the per-asset compute-sizing payoff lives.
 *   4. `Promise.allSettled` waits for every child to either succeed
 *      or fail. Failed children have already marked their asset rows
 *      `failed` inside `dispatchAsset`, so the parent does not need
 *      to do any DB writes for failures here.
 *   5. After every child has settled, enqueue a single creative
 *      review BullMQ job (the review queue is still consumed by the
 *      worker service — only the generation stage moves to Workflows
 *      in this migration).
 *   6. Flip the project status to `reviewing` and publish a
 *      `phase_complete: generating` event so the dashboard cuts over
 *      from the "generating" card to the "reviewing" card.
 *
 * The parent itself runs on a cheap `starter` instance — all it does
 * is two DB reads, a small amount of dispatch logic, and a Redis
 * publish. The heavy lifting happens in the chained child runs.
 *
 * Partial failure is an intentional first-class state: if one video
 * render fails but eight text assets succeed, the review still runs
 * on the eight succeeded assets. The `Promise.allSettled` guarantees
 * we do not short-circuit on the first rejection.
 */

const PARENT_TIMEOUT_SECONDS = 30 * 60;

async function dispatchChildTask(asset: {
  id: string;
  projectId: string;
  type: AssetType;
}): Promise<void> {
  const input = { projectId: asset.projectId, assetId: asset.id };

  // The task wrapper from `@renderinc/sdk/workflows` types each
  // registered task as `TaskFunction<TArgs, TResult>` which returns
  // `TResult | Promise<TResult>` — the wrapped function is allowed to
  // be sync or async. Awaiting every call here normalises the switch
  // branches to `Promise<void>` and lets this helper present a clean
  // async return signature to `Promise.allSettled`.
  switch (asset.type) {
    case 'blog_post':
    case 'twitter_thread':
    case 'linkedin_post':
    case 'product_hunt_description':
    case 'hacker_news_post':
    case 'faq':
    case 'changelog_entry':
    case 'voiceover_script':
    case 'tips':
      await generateWrittenAsset(input);
      return;
    case 'og_image':
    case 'social_card':
      await generateImageAsset(input);
      return;
    case 'product_video':
    case 'video_storyboard':
      await generateVideoAsset(input);
      return;
    case 'voice_commercial':
    case 'podcast_script':
      await generateAudioAsset(input);
      return;
    case 'world_scene':
      await generateWorldScene(input);
      return;
    case 'outreach_draft':
    case 'per_commit_teaser':
      // Phase 6 commit-marketing asset types. These are never
      // produced by the launch-kit fan-out — they are generated by
      // `process-commit-marketing-run.ts` in the worker via the
      // outreach-draft agent and the commit-marketability agent on a
      // completely separate code path (webhook → commit marketing
      // run → per-influencer drafts). Rejecting here is the correct
      // invariant: if one of these types is ever `status='queued'`
      // during a regular generation fan-out, the DB got into a
      // state the pipeline does not model, and silently routing it
      // through a wrong agent (as the old BullMQ path did via the
      // writer's fall-through) would hide the bug.
      throw new Error(
        `generateAllAssetsForProject: asset type "${asset.type}" is produced by the commit marketing run, not the launch-kit fan-out. This asset should not be in status="queued" on a regular project.`
      );
    default: {
      // Exhaustiveness check — if `AssetType` grows a new variant and
      // this switch is not updated, TypeScript will refuse to compile.
      const exhaustive: never = asset.type;
      throw new Error(
        `generateAllAssetsForProject: no child task routing for asset type "${String(exhaustive)}"`
      );
    }
  }
}

export const generateAllAssetsForProject = task<[AllAssetsInput], void>(
  {
    name: 'generateAllAssetsForProject',
    plan: 'starter',
    timeoutSeconds: PARENT_TIMEOUT_SECONDS,
    retry: {
      maxRetries: 1,
      waitDurationMs: 5000,
      backoffScaling: 2,
    },
  },
  async function generateAllAssetsForProject(
    input: AllAssetsInput
  ): Promise<void> {
    const parsed = AllAssetsInputSchema.parse(input);
    const { projectId } = parsed;

    // ── Read the project + its assets in a single query
    const project = await db.query.projects.findFirst({
      where: eq(schema.projects.id, projectId),
      with: { assets: true },
    });
    if (!project) {
      throw new Error(
        `generateAllAssetsForProject: project ${projectId} not found`
      );
    }
    if (!project.strategy || !project.repoAnalysis || !project.research) {
      throw new Error(
        `generateAllAssetsForProject: project ${projectId} not ready for generation (missing strategy / repo analysis / research)`
      );
    }

    const queuedAssets = project.assets.filter((a) => a.status === 'queued');

    if (queuedAssets.length === 0) {
      console.log(
        `[Workflows:Parent] No queued assets for project ${projectId} — nothing to do`
      );
      return;
    }

    await projectProgressPublisher.phaseStart(
      projectId,
      'generating',
      `Generating ${queuedAssets.length} assets in parallel`
    );

    // ── Fan out to child tasks via run chaining
    const results = await Promise.allSettled(
      queuedAssets.map((asset) =>
        dispatchChildTask({
          id: asset.id,
          projectId: asset.projectId,
          type: asset.type,
        })
      )
    );

    // Log rejected children for the run's stdout — the asset rows
    // themselves have already been marked `failed` inside
    // `dispatchAsset`, so nothing else needs to happen DB-side for
    // the failures. The console log gives the Render run page a
    // human-readable trace.
    for (let i = 0; i < results.length; i += 1) {
      const result = results[i];
      const asset = queuedAssets[i];
      if (result && result.status === 'rejected' && asset) {
        const reason =
          result.reason instanceof Error
            ? result.reason.message
            : String(result.reason);
        console.error(
          `[Workflows:Parent] Asset ${asset.id} (${asset.type}) failed: ${reason}`
        );
      }
    }

    // ── Enqueue the review BullMQ job with every asset id on the
    //    project, not just the freshly-generated subset. This is a
    //    deliberate parity preservation with the worker's
    //    `checkAndTriggerReview` (apps/worker/src/index.ts:358-399)
    //    which reads every asset row via `db.query.assets.findMany`
    //    and passes `projectAssets.map((a) => a.id)` to the review
    //    job. The review processor at
    //    `apps/worker/src/processors/review-generated-assets.ts:47-57`
    //    then filters that id set by `status === 'reviewing' ||
    //    'complete'` to decide which ones to re-grade. Passing only
    //    the queued subset here would silently diverge from the
    //    BullMQ path on a revision round — the behavior delta
    //    between the two paths must be zero while both coexist
    //    behind the feature flag.
    const assetIds = project.assets.map((a) => a.id);
    await enqueueReviewJob({
      projectId,
      assetIds,
      revisionCount: project.revisionCount,
    });

    // ── Flip the project status to `reviewing` so the dashboard's
    //    project card transitions out of the generating state.
    //    No `phase_complete: generating` event is published here —
    //    the BullMQ path's `checkAndTriggerReview` does not emit one
    //    either, and introducing a new event could confuse a
    //    dashboard state machine that expects a specific sequence.
    //    The status-update consumer reads the DB flip via the next
    //    SSE tick.
    await db
      .update(schema.projects)
      .set({ status: 'reviewing', updatedAt: new Date() })
      .where(eq(schema.projects.id, projectId));

    console.log(
      `[Workflows:Parent] Project ${projectId} all ${queuedAssets.length} assets settled, review enqueued`
    );
  }
);
