import {
  Routes,
  Route,
  useNavigate,
  useParams,
  useLocation,
  useSearchParams,
  Link,
  Navigate,
} from 'react-router-dom';
import { motion, AnimatePresence, useReducedMotion } from 'framer-motion';
import { RocketLaunch } from '@phosphor-icons/react';
import { RepositoryUrlForm } from './components/RepositoryUrlForm.js';
import { ProjectSummaryList } from './components/ProjectSummaryList.js';
import { ProjectDetailView } from './components/ProjectDetailView.js';
import { TrendsPage } from './components/TrendsPage.js';
import { CreatePage } from './components/CreatePage.js';
import { LandingPage } from './components/LandingPage.js';
import { ErrorBoundary } from './components/ErrorBoundary.js';
import { useProjectListData } from './hooks/useProjectData.js';

function HomePage() {
  const navigate = useNavigate();
  const { projects, loading, refresh } = useProjectListData();
  const shouldReduceMotion = useReducedMotion();
  // Pre-fill the repository form from a `?repo=` query param so the
  // marketing landing page at `/` can forward whatever the user
  // typed in its hero input. Read once — any subsequent edit the
  // user makes lives in the form's local state.
  const [searchParams] = useSearchParams();
  const initialRepoUrl = searchParams.get('repo') ?? undefined;

  const handleProjectCreated = (id: string) => {
    void navigate(`/projects/${id}`);
  };

  return (
    <div className="min-h-screen relative">
      {/* Subtle ambient background — radial accent gradient that
          breathes behind the hero, hand-painted in CSS so it ships
          with no extra asset weight. */}
      <div className="pointer-events-none absolute inset-x-0 top-0 h-[480px] overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-accent-500/5 via-transparent to-transparent" />
        <motion.div
          className="absolute left-1/2 top-0 h-[420px] w-[820px] -translate-x-1/2 rounded-full bg-accent-500/10 blur-[120px]"
          initial={{ opacity: 0 }}
          animate={shouldReduceMotion ? { opacity: 0.5 } : { opacity: [0.4, 0.7, 0.4] }}
          transition={
            shouldReduceMotion
              ? { duration: 0.4, ease: 'easeOut' }
              : {
                  duration: 6,
                  repeat: Infinity,
                  ease: 'easeInOut',
                }
          }
        />
      </div>

      {/* Hero Section */}
      <motion.header
        className="border-b border-surface-800 relative"
        initial={{ opacity: 0, y: -16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
      >
        <div className="max-w-6xl mx-auto px-6 py-8">
          <motion.div
            className="flex items-center gap-3 mb-2"
            initial={{ opacity: 0, x: -8 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.1, duration: 0.4 }}
          >
            <Link to="/" className="flex items-center gap-3 group">
              <motion.div
                className="w-8 h-8 rounded-lg bg-accent-500 flex items-center justify-center relative"
                whileHover={{ scale: 1.08, rotate: -4 }}
                transition={{ type: 'spring', stiffness: 360, damping: 20 }}
              >
                <RocketLaunch weight="fill" size={18} className="text-white" />
                <span className="absolute inset-0 rounded-lg bg-accent-500/40 blur-md -z-10" />
              </motion.div>
              <h1 className="font-display text-display-md text-text-primary group-hover:text-accent-400 transition-colors">
                LaunchKit
              </h1>
            </Link>
          </motion.div>
          <div className="flex items-start justify-between">
            <motion.p
              className="text-body-lg text-text-secondary max-w-xl"
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.18, duration: 0.5 }}
            >
              Paste a GitHub repo. Get a full go-to-market kit generated by an AI
              team that researches, strategizes, creates, and learns.
            </motion.p>
            <motion.div
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.22, duration: 0.4 }}
            >
              <Link
                to="/create"
                className="inline-flex items-center gap-2 rounded-lg border border-surface-700/60 bg-surface-900/50 px-4 py-2 text-body-sm font-medium text-text-muted hover:border-accent-500/40 hover:text-accent-400 transition-colors whitespace-nowrap"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                </svg>
                Create manually
              </Link>
            </motion.div>
          </div>
        </div>
      </motion.header>

      {/* Input Section */}
      <motion.section
        className="border-b border-surface-800 relative"
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.25, duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
      >
        <div className="max-w-6xl mx-auto px-6 py-12">
          <RepositoryUrlForm
            onProjectCreated={handleProjectCreated}
            {...(initialRepoUrl !== undefined ? { initialUrl: initialRepoUrl } : {})}
          />
        </div>
      </motion.section>

      {/* Projects */}
      <motion.section
        className="max-w-6xl mx-auto px-6 py-8"
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.35, duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
      >
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-4">
            <h2 className="label">Projects</h2>
            <Link
              to="/trends"
              className="text-body-xs text-accent-400 hover:text-accent-300 transition-colors font-mono"
            >
              Trending Topics
            </Link>
          </div>
          <button onClick={refresh} className="btn-ghost text-body-xs">
            Refresh
          </button>
        </div>
        <ProjectSummaryList projects={projects} loading={loading} />
      </motion.section>
    </div>
  );
}

function ProjectPage() {
  const { id } = useParams<{ id: string }>();
  if (!id) return null;

  return (
    <div className="min-h-screen">
      {/* Nav */}
      <motion.header
        className="border-b border-surface-800"
        initial={{ opacity: 0, y: -8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
      >
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center gap-3">
          <Link to="/app" className="flex items-center gap-3 group">
            <motion.div
              className="w-6 h-6 rounded bg-accent-500 flex items-center justify-center"
              whileHover={{ scale: 1.12, rotate: -6 }}
              transition={{ type: 'spring', stiffness: 360, damping: 20 }}
            >
              <RocketLaunch weight="fill" size={14} className="text-white" />
            </motion.div>
            <span className="font-display text-heading-md text-text-primary group-hover:text-accent-400 transition-colors">
              LaunchKit
            </span>
          </Link>
        </div>
      </motion.header>

      <ProjectDetailView projectId={id} />
    </div>
  );
}

function TrendsPageWrapper() {
  return (
    <div className="min-h-screen">
      <motion.header
        className="border-b border-surface-800"
        initial={{ opacity: 0, y: -8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
      >
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center gap-3">
          <Link to="/app" className="flex items-center gap-3 group">
            <motion.div
              className="w-6 h-6 rounded bg-accent-500 flex items-center justify-center"
              whileHover={{ scale: 1.12, rotate: -6 }}
              transition={{ type: 'spring', stiffness: 360, damping: 20 }}
            >
              <RocketLaunch weight="fill" size={14} className="text-white" />
            </motion.div>
            <span className="font-display text-heading-md text-text-primary group-hover:text-accent-400 transition-colors">
              LaunchKit
            </span>
          </Link>
        </div>
      </motion.header>
      <TrendsPage />
    </div>
  );
}

function CreatePageWrapper() {
  return (
    <div className="min-h-screen">
      <motion.header
        className="border-b border-surface-800"
        initial={{ opacity: 0, y: -8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
      >
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center gap-3">
          <Link to="/app" className="flex items-center gap-3 group">
            <motion.div
              className="w-6 h-6 rounded bg-accent-500 flex items-center justify-center"
              whileHover={{ scale: 1.12, rotate: -6 }}
              transition={{ type: 'spring', stiffness: 360, damping: 20 }}
            >
              <RocketLaunch weight="fill" size={14} className="text-white" />
            </motion.div>
            <span className="font-display text-heading-md text-text-primary group-hover:text-accent-400 transition-colors">
              LaunchKit
            </span>
          </Link>
        </div>
      </motion.header>
      <CreatePage />
    </div>
  );
}

export default function App() {
  // `useLocation()` lets AnimatePresence diff routes by pathname, so
  // navigating between Home and Project Detail produces a clean
  // cross-fade instead of a jarring DOM swap.
  const location = useLocation();

  return (
    <AnimatePresence mode="popLayout">
      <motion.div
        key={location.pathname}
        initial={false}
        animate={{ opacity: 1, y: 0, pointerEvents: 'auto' as const }}
        exit={{ opacity: 0, y: -8, pointerEvents: 'none' as const }}
        transition={{ duration: 0.32, ease: [0.16, 1, 0.3, 1] }}
      >
        <ErrorBoundary>
          <Routes location={location}>
            <Route path="/" element={<LandingPage />} />
            <Route path="/app" element={<HomePage />} />
            <Route path="/trends" element={<TrendsPageWrapper />} />
            <Route path="/create" element={<CreatePageWrapper />} />
            <Route path="/projects/:id" element={<ProjectPage />} />
            <Route path="*" element={<Navigate to="/" replace />} />
          </Routes>
        </ErrorBoundary>
      </motion.div>
    </AnimatePresence>
  );
}
