import { Routes, Route, useNavigate, useParams } from 'react-router-dom';
import { RepoInput } from './components/RepoInput.js';
import { ProjectList } from './components/ProjectList.js';
import { ProjectView } from './components/ProjectView.js';
import { useProjects } from './hooks/useProject.js';

function HomePage() {
  const navigate = useNavigate();
  const { projects, loading, refresh } = useProjects();

  const handleProjectCreated = (id: string) => {
    navigate(`/projects/${id}`);
  };

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <header className="border-b border-surface-800">
        <div className="max-w-6xl mx-auto px-6 py-8">
          <div className="flex items-center gap-3 mb-2">
            <div className="w-8 h-8 rounded-lg bg-accent-500 flex items-center justify-center">
              <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
            </div>
            <h1 className="font-mono text-xl font-bold tracking-tight">LaunchKit</h1>
          </div>
          <p className="text-surface-400 text-lg max-w-xl">
            Paste a GitHub repo. Get a full go-to-market kit generated by an AI team
            that researches, strategizes, creates, and learns.
          </p>
        </div>
      </header>

      {/* Input Section */}
      <section className="border-b border-surface-800">
        <div className="max-w-6xl mx-auto px-6 py-12">
          <RepoInput onProjectCreated={handleProjectCreated} />
        </div>
      </section>

      {/* Projects */}
      <section className="max-w-6xl mx-auto px-6 py-8">
        <div className="flex items-center justify-between mb-6">
          <h2 className="font-mono font-semibold text-surface-400 text-sm uppercase tracking-wider">
            Projects
          </h2>
          <button onClick={refresh} className="btn-ghost text-xs">
            Refresh
          </button>
        </div>
        <ProjectList projects={projects} loading={loading} />
      </section>
    </div>
  );
}

function ProjectPage() {
  const { id } = useParams<{ id: string }>();
  if (!id) return null;

  return (
    <div className="min-h-screen">
      {/* Nav */}
      <header className="border-b border-surface-800">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center gap-3">
          <div className="w-6 h-6 rounded bg-accent-500 flex items-center justify-center">
            <svg className="w-3.5 h-3.5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
            </svg>
          </div>
          <span className="font-mono text-sm font-bold tracking-tight">LaunchKit</span>
        </div>
      </header>

      <ProjectView projectId={id} />
    </div>
  );
}

export default function App() {
  return (
    <Routes>
      <Route path="/" element={<HomePage />} />
      <Route path="/projects/:id" element={<ProjectPage />} />
    </Routes>
  );
}
