import {
  Routes,
  Route,
  useNavigate,
  useParams,
  useLocation,
  Link,
} from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { RepositoryUrlForm } from './components/RepositoryUrlForm.js';
import { ProjectSummaryList } from './components/ProjectSummaryList.js';
import { ProjectDetailView } from './components/ProjectDetailView.js';
import { useProjectListData } from './hooks/useProjectData.js';

function HomePage() {
  const navigate = useNavigate();
  const { projects, loading, refresh } = useProjectListData();

  const handleProjectCreated = (id: string) => {
    void navigate(`/projects/${id}`);
  };

  return (
    <div className="min-h-screen relative">
      {/* Subtle ambient background — radial accent gradient that
          breathes behind the hero, hand-painted in CSS so it ships
          with no extra asset weight. */}
      <div className="pointer-events-none absolute inset-x-0 top-0 h-[480px] overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-accent-500/5 via-transparent to-transparent" />
        <motion.div
          className="absolute left-1/2 top-0 h-[420px] w-[820px] -translate-x-1/2 rounded-full bg-accent-500/10 blur-[120px]"
          initial={{ opacity: 0 }}
          animate={{ opacity: [0.4, 0.7, 0.4] }}
          transition={{
            duration: 6,
            repeat: Infinity,
            ease: 'easeInOut',
          }}
        />
      </div>

      {/* Hero Section */}
      <motion.header
        className="border-b border-surface-800 relative"
        initial={{ opacity: 0, y: -16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
      >
        <div className="max-w-6xl mx-auto px-6 py-8">
          <motion.div
            className="flex items-center gap-3 mb-2"
            initial={{ opacity: 0, x: -8 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.1, duration: 0.4 }}
          >
            <motion.div
              className="w-8 h-8 rounded-lg bg-accent-500 flex items-center justify-center relative"
              whileHover={{ scale: 1.08, rotate: -4 }}
              transition={{ type: 'spring', stiffness: 360, damping: 20 }}
            >
              <svg
                className="w-5 h-5 text-white"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M13 10V3L4 14h7v7l9-11h-7z"
                />
              </svg>
              {/* Soft glow halo */}
              <span className="absolute inset-0 rounded-lg bg-accent-500/40 blur-md -z-10" />
            </motion.div>
            <h1 className="font-mono text-xl font-bold tracking-tight">
              LaunchKit
            </h1>
          </motion.div>
          <motion.p
            className="text-surface-400 text-lg max-w-xl"
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.18, duration: 0.5 }}
          >
            Paste a GitHub repo. Get a full go-to-market kit generated by an AI
            team that researches, strategizes, creates, and learns.
          </motion.p>
        </div>
      </motion.header>

      {/* Input Section */}
      <motion.section
        className="border-b border-surface-800 relative"
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.25, duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
      >
        <div className="max-w-6xl mx-auto px-6 py-12">
          <RepositoryUrlForm onProjectCreated={handleProjectCreated} />
        </div>
      </motion.section>

      {/* Projects */}
      <motion.section
        className="max-w-6xl mx-auto px-6 py-8"
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.35, duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
      >
        <div className="flex items-center justify-between mb-6">
          <h2 className="font-mono font-semibold text-surface-400 text-sm uppercase tracking-wider">
            Projects
          </h2>
          <button onClick={refresh} className="btn-ghost text-xs">
            Refresh
          </button>
        </div>
        <ProjectSummaryList projects={projects} loading={loading} />
      </motion.section>
    </div>
  );
}

function ProjectPage() {
  const { id } = useParams<{ id: string }>();
  if (!id) return null;

  return (
    <div className="min-h-screen">
      {/* Nav */}
      <motion.header
        className="border-b border-surface-800"
        initial={{ opacity: 0, y: -8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
      >
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center gap-3">
          <Link to="/" className="flex items-center gap-3 group">
            <motion.div
              className="w-6 h-6 rounded bg-accent-500 flex items-center justify-center"
              whileHover={{ scale: 1.12, rotate: -6 }}
              transition={{ type: 'spring', stiffness: 360, damping: 20 }}
            >
              <svg
                className="w-3.5 h-3.5 text-white"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M13 10V3L4 14h7v7l9-11h-7z"
                />
              </svg>
            </motion.div>
            <span className="font-mono text-sm font-bold tracking-tight group-hover:text-accent-400 transition-colors">
              LaunchKit
            </span>
          </Link>
        </div>
      </motion.header>

      <ProjectDetailView projectId={id} />
    </div>
  );
}

export default function App() {
  // `useLocation()` lets AnimatePresence diff routes by pathname, so
  // navigating between Home and Project Detail produces a clean
  // cross-fade instead of a jarring DOM swap.
  const location = useLocation();

  return (
    <AnimatePresence mode="wait">
      <motion.div
        key={location.pathname}
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, y: -8 }}
        transition={{ duration: 0.32, ease: [0.16, 1, 0.3, 1] }}
      >
        <Routes location={location}>
          <Route path="/" element={<HomePage />} />
          <Route path="/projects/:id" element={<ProjectPage />} />
        </Routes>
      </motion.div>
    </AnimatePresence>
  );
}
